=== DavidLopNun/LM/Actividad 4/CocinasSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Cocinas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Cocina" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ubicaciÃ³n" type="xs:string"/>
              <xs:element name="espacio" type="xs:string"/>
              <xs:element name="cocinero">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="experiencia" type="xs:string"/>
                    <xs:element name="edad" type="xs:integer"/>
                  </xs:sequence>
                  <xs:attribute name="ID" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="IDC" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== DavidLopNun/LM/Actividad 4/Cocinas/Cocinas-X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Cocinas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.gmrv.es CocinasSchema.xsd">

<Cocinas>
    <Cocina IDC="1">
        <ubicación>Cadiz</ubicación>
        <espacio>50m cuadrados</espacio>
        <cocinero ID="1">
            <nombre>David Lopez</nombre>
            <experiencia>Alta</experiencia>
            <edad>19</edad>
        </cocinero>
    </Cocina>

    <Cocina IDC="2">
        <ubicación>Granada</ubicación>
        <espacio>60m cuadrados</espacio>
        <cocinero ID="2">
            <nombre>Maria Perez</nombre>
            <experiencia>Alta</experiencia>
            <edad>50</edad>
        </cocinero>
    </Cocina>

    <Cocina IDC="3">
        <ubicación>Sevilla</ubicación>
        <espacio>30m cuadrados</espacio>
        <cocinero ID="3">
            <nombre>Juan Garcia</nombre>
            <experiencia>Media</experiencia>
            <edad>27</edad>
        </cocinero>
    </Cocina>
</Cocinas>
