=== DavidLopNun/LM/Actividad 5/Alumnado/Alumnado.dtd
<!ELEMENT Alumnado (Alumno+)>
<!ELEMENT Alumno (NIF, resultado, observaciones, IP_Mac)>

<!ELEMENT NIF (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT IP_Mac (#PCDATA)>

=== DavidLopNun/LM/Actividad 5/Alumnado-D.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Alumnado SYSTEM "Alumnado.dtd">

<Alumnado>
    <Alumno>
        <NIF>77496750k</NIF>
        <resultado>Apto</resultado>
        <observaciones>Realiza buen proyecto</observaciones>
        <IP_Mac>IP</IP_Mac>
    </Alumno>

    <Alumno>
        <NIF>77496777k</NIF>
        <resultado>Apto</resultado>
        <observaciones></observaciones>
        <IP_Mac>MAC</IP_Mac>
    </Alumno>

    <Alumno>
        <NIF>77496666k</NIF>
        <resultado>No apto</resultado>
        <observaciones>No realiza proyecto</observaciones>
        <IP_Mac>IP</IP_Mac>
    </Alumno>
</Alumnado>
