=== DavidLopNun/LM/Actividad 4/Gestoria/Gestoria.dtd
<!ELEMENT Gestoria (Clientes)>
<!ELEMENT Clientes (sede+)>
<!ELEMENT sede (nomEmpleado, fechaAlta, Cliente+)>
<!ATTLIST sede codigoS CDATA #REQUIRED>

<!ELEMENT nomEmpleado (#PCDATA)>
<!ELEMENT fechaAlta (#PCDATA)>

<!ELEMENT Cliente (descripcion, nViviendas, vivienda+)>
<!ATTLIST Cliente codigoC CDATA #REQUIRED>

<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT nViviendas (#PCDATA)>
<!ELEMENT vivienda (coste, resumen, plazoHac)>
<!ATTLIST vivienda codigoV CDATA #REQUIRED>

<!ELEMENT coste (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT plazoHac (#PCDATA)>

=== DavidLopNun/LM/Actividad 4/Gestoria/Gestoria-D.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Gestoria SYSTEM "Gestoria.dtd">

<Gestoria>
    <Clientes>
            <sede codigoS="1">
               <nomEmpleado>Juan Garcia</nomEmpleado>
               <fechaAlta>10/03/2022</fechaAlta>
               <Cliente codigoC="1">
                  <descripcion>solvente</descripcion>
                  <nViviendas>2</nViviendas>
                  <vivienda codigoV="1">
                     <coste>200.000</coste>
                     <resumen>Casa en Ubrique</resumen>
                     <plazoHac>1</plazoHac>
                   </vivienda>
                   <vivienda codigoV="2">
                    <coste>550.000</coste>
                    <resumen>Casa en Ubrique</resumen>
                    <plazoHac>1</plazoHac>
                  </vivienda>
               </Cliente>
               <Cliente codigoC="2">
                <descripcion>insolvente</descripcion>
                <nViviendas>1</nViviendas>
                <vivienda codigoV="3">
                    <coste>400.000</coste>
                    <resumen>Casa en Madrid</resumen>
                    <plazoHac>10</plazoHac>
                </vivienda>
             </Cliente>
            </sede>

            <sede codigoS="2">
                <nomEmpleado>Carlos Moreno</nomEmpleado>
                <fechaAlta>01/03/2020</fechaAlta>
                <Cliente codigoC="3">
                   <descripcion>solvente</descripcion>
                   <nViviendas>3</nViviendas>
                   <vivienda codigoV="4">
                      <coste>200.000</coste>
                      <resumen>Casa en Mallorca</resumen>
                      <plazoHac>2</plazoHac>
                   </vivienda>
                   <vivienda codigoV="5">
                    <coste>500.000</coste>
                    <resumen>Casa en Mallorca</resumen>
                    <plazoHac>5</plazoHac>
                 </vivienda>
                 <vivienda codigoV="6">
                    <coste>1.000.000</coste>
                    <resumen>Casa en Mallorca</resumen>
                    <plazoHac>10</plazoHac>
                 </vivienda>
                </Cliente>
                <Cliente codigoC="4">
                 <descripcion>insolvente</descripcion>
                 <nViviendas>1</nViviendas>
                 <vivienda codigoV="7">
                    <coste>10.000.000</coste>
                    <resumen>Casa en Ibiza</resumen>
                    <plazoHac>15</plazoHac>
                 </vivienda>
              </Cliente>
             </sede>
             <sede codigoS="3">
                <nomEmpleado>Daniel OÃ±ate</nomEmpleado>
                <fechaAlta>29/01/2009</fechaAlta>
                <Cliente codigoC="5">
                   <descripcion>insolvente</descripcion>
                   <nViviendas>1</nViviendas>
                   <vivienda codigoV="8">
                    <coste>5.000.000</coste>
                    <resumen>Casa en Barcelona</resumen>
                    <plazoHac>10</plazoHac>
                 </vivienda>
                </Cliente>
                <Cliente codigoC="6">
                 <descripcion>insolvente</descripcion>
                 <nViviendas>1</nViviendas>
                 <vivienda codigoV="9">
                    <coste>80.000</coste>
                    <resumen>Casa en Benaocaz</resumen>
                    <plazoHac>10</plazoHac>
                 </vivienda>
              </Cliente>
             </sede>
    </Clientes>
</Gestoria>
