=== DavidLopNun/LM/Actividad 7/Productos.dtd
<!ELEMENT Productos (producto+)>
<!ELEMENT producto (nombre, precio, disponible, detalles)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT disponible (#PCDATA)>
<!ELEMENT detalles (color, talla)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT talla (#PCDATA)>

=== DavidLopNun/LM/Actividad 7/Productos/Productos-D.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Productos SYSTEM "Productos.dtd">

<Productos>
    <producto>
      <nombre>Camiseta</nombre>
      <precio>19.99</precio>
      <disponible>true</disponible>
      <detalles>
        <color>Rojo</color>
        <talla>M</talla>
      </detalles>
    </producto>
    <producto>
      <nombre>Pantal√≥n</nombre>
      <precio>29.99</precio>
      <disponible>false</disponible>
      <detalles>
        <color>Azul</color>
        <talla>L</talla>
      </detalles>
    </producto>
  </Productos>
