=== DavidLopNun/LM/Actividad 3/Equipos/EquiposSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Equipos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="equipo" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="colorEquipacion" type="xs:string"/>
              <xs:element name="marcaEquipacion" type="xs:string"/>
              <xs:element name="posicion" type="xs:integer"/>
              <xs:element name="entrenador" type="xs:string"/>
              <xs:element name="presidente" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== DavidLopNun/LM/Actividad 3/Equipos/Equipos-X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Equipos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.gmrv.es EquiposSchema.xsd">
<Equipos>
    <equipo>
        <colorEquipacion>Blanca </colorEquipacion>
        <marcaEquipacion>Adidas</marcaEquipacion>
        <posicion>2</posicion>
        <entrenador>Ancelotti</entrenador>
        <presidente>Florentino</presidente>
    </equipo>

    <equipo>
        <colorEquipacion>Blaugrana </colorEquipacion>
        <marcaEquipacion>Nike</marcaEquipacion>
        <posicion>4</posicion>
        <entrenador>Xavi</entrenador>
        <presidente>Laporta</presidente>
    </equipo>

    <equipo>
        <colorEquipacion>Verde y blanca </colorEquipacion>
        <marcaEquipacion>Hummel</marcaEquipacion>
        <posicion>7</posicion>
        <entrenador>Pellegrini</entrenador>
        <presidente>Haro</presidente>
    </equipo>
</Equipos>
