=== DavidLopNun/LM/Actividad 7/Editorial/EditorialSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Editorial">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="edicion" type="xs:string"/>
        <xs:element name="descripcion" type="xs:string"/>
        <xs:element name="fecha" type="xs:string"/>
        <xs:element name="region" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="trimestre" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="librosVendidos" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="zona" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== DavidLopNun/LM/Actividad 7/Editorial/Editorial-X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Editorial xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EditorialSchema.xsd">

        <edicion>Aranda</edicion>
        <descripcion>Informe de ventas para las regiones Norte, Centro y Sur</descripcion>
        <fecha>30/12/2009</fecha>
        <region zona="Norte">
            <trimestre id="1">
                <librosVendidos>24000</librosVendidos>
            </trimestre>
            <trimestre id="2">
                <librosVendidos>38600</librosVendidos>
            </trimestre>
            <trimestre id="3">
                <librosVendidos>NO_INFO</librosVendidos>
            </trimestre>
            <trimestre id="4">
                <librosVendidos>NO_INFO</librosVendidos>
            </trimestre>
        </region>
    
        <region zona="Centro">
            <trimestre id="1">
                <librosVendidos>NO_INFO</librosVendidos>
            </trimestre>
            <trimestre id="2">
                <librosVendidos>16080</librosVendidos>
            </trimestre>
            <trimestre id="3">
                <librosVendidos>25000</librosVendidos>
            </trimestre>
            <trimestre id="4">
                <librosVendidos>29000</librosVendidos>
            </trimestre>
        </region>
    
        <region zona="Sur">
            <trimestre id="1">
                <librosVendidos>27000</librosVendidos>
            </trimestre>
            <trimestre id="2">
                <librosVendidos>31400</librosVendidos>
            </trimestre>
            <trimestre id="3">
                <librosVendidos>40100</librosVendidos>
            </trimestre>
            <trimestre id="4">
                <librosVendidos>30000</librosVendidos>
            </trimestre>
        </region>
    </Editorial>
