=== DavidLopNun/LM/Actividad 6/Escuderias/EscuderiasSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Escuderias">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="escuderia" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombreE" type="xs:string"/>
              <xs:element name="jefe">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombreJ" type="xs:string"/>
                    <xs:element name="edad" type="xs:integer"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== DavidLopNun/LM/Actividad 6/Escuderias/Escuderias-X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Escuderias xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.gmrv.es EscuderiasSchema.xsd">

    <Escuderias>
        <escuderia>
            <nombreE>Ferrari</nombreE>
            <jefe>
                <nombreJ>Fred Vasseur</nombreJ>
                <edad>54</edad>
            </jefe>
        </escuderia>
    
        <escuderia>
            <nombreE>Red Bull</nombreE>
            <jefe>
                <nombreJ>Christian Horner</nombreJ>
                <edad>50</edad>
            </jefe>
        </escuderia>
    
        <escuderia>
            <nombreE>Mercedes</nombreE>
            <jefe>
                <nombreJ>Toto Wolff</nombreJ>
                <edad>52</edad>
            </jefe>
        </escuderia>
    </Escuderias>
